### ISSUE TITLE
Create an album

### ISSUE THREAD

**Issue by elderapo** [rmp135/imgur#2]
Hey! How can I create an album and add some images to it (either previously uploaded or new)?

**Comment by rmp135** [comment]
Turns out I'd never written the album endpoints. They've been added in 0.5.0.

You can create an album and add images to it using the [Album.create](https://rmp135.github.io/imgur/api/album/#create) function.

```javascript
client.Album.create({ title: "some title", ids: ["imageId1", "imageId2"] })
```

In order to add new images to an album, you'll have to upload them using the [Image.upload](https://rmp135.github.io/imgur/api/image/#upload) function. Then, using the returned image id, add it to the album. There's some functions in there to aid with adding images to existing albums.
